
weigth_matrix:
  mat_path: "../data/small_02_EVENT_[2s_TR]_[1s_DUR]_[6s_ISI]_[100_TRIALS].mat"
  N_ROIs: 100
  sigma: 0.1
  num_modules: 4
  norm_type: "cols"
  gen_type: "simple_prod"

sym_parameters:
  delay: 250
  rest_before: True
  first_duration: 6
  last_duration: 20
  long_rest: 60
  normalize_max: 0.001


wc_params:
  'exc_ext': 0.758
  'K_gl': 2.63
  'sigma_ou': 0.0035
  'inh_ext': 0
  'a_exc': 1.5
  'a_inh': 1.5
  'c_excexc': 16
  'c_excinh': 15
  'c_inhexc': 12
  'c_inhinh': 3
  'mu_exc': 3
  'mu_inh': 3
  'tau_exc': 2.5
  'tau_inh': 3.75
  'signalV': 10


bw_params:
  k:
    value: 0.65
    variance: 0.015
  gamma:
    value: 0.41
    variance: 0.008  # 0.002 * 4
  tau:
    value: 2.5
    variance: 0.2272  # 0.0568 * 4
  alpha:
    value: 0.32
    variance: 0.006  # 0.0015 * 4
  rho:
    value: 0.34
    variance: 0.0096  # 0.0024 * 4

  normalize_max: 1.0
  length: 32 #time length (in seconds)
  duration: 0.001


time_resolution:
  TR: 2
  fMRI_T: 16

rest_duration: 900 #in seconds





